### ISSUE TITLE
Any new progress?

### ISSUE THREAD

**Issue by lordfriend** [RoyaAoki/Megumin#1]
If you have any progress or need help, let me know. If you release a full featured version. I'll add some link to recommend in Web Client and Github.

**Comment by RoyaAoki** [comment]
This project are planned as a watch only client, And all planned features are near finished (with few fixes). I‘m working on the Player recently, it seems will take a while longer.
I plan to fix the issues first, until that, for most users, it should ready to go.

**Comment by lordfriend** [comment]
Thank you for your effort. Once you have released a production ready version. It's suggested to publish on Google Play.
